---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint:
  name: yamllint
platforms:
  - name: win2016
    box: jborean93/WindowsServer2016
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        mycustom_var: "Hello from molecule definition file"
  connection_options:
    ansible_user: "vagrant"
    ansible_password: "vagrant"
    ansible_port: 55985
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
ansible:
